"""update outputs table and add outputs_files table

Revision ID: 1d88d95ae783
Revises: efc4b7e31981
Create Date: 2024-11-30 00:38:04.992152

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d88d95ae783"
down_revision: Union[str, None] = "efc4b7e31981"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "output_file",
        sa.Column("output_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["output_id"],
            ["outputs.id"],
        ),
        sa.PrimaryKeyConstraint("output_id", "file_id"),
    )
    op.add_column("outputs", sa.Column("title", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outputs", "title")
    op.drop_table("output_file")
    # ### end Alembic commands ###
