"""add answers table

Revision ID: 5dac468e846d
Revises: 0466229c861e
Create Date: 2024-12-26 15:16:16.597705

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5dac468e846d"
down_revision: Union[str, None] = "0466229c861e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answers",
        "title",
        existing_type=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_answers_title"), "answers", ["title"], unique=False)
    op.create_index(op.f("ix_answers_user_id"), "answers", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answers_user_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_title"), table_name="answers")
    op.alter_column(
        "answers",
        "title",
        existing_type=sa.String(length=256),
        type_=mysql.TEXT(collation="utf8mb4_unicode_ci"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
