"""add user_answer

Revision ID: 0466229c861e
Revises: a03982887391
Create Date: 2024-12-15 00:59:03.102362

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0466229c861e"
down_revision: Union[str, None] = "a03982887391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_user_answers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("answer", sa.TEXT(), nullable=False),
        sa.Column("scoring_results", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_user_answers_exercise_id"),
        "exercise_user_answers",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exercise_user_answers_id"), "exercise_user_answers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_user_answers_user_id"), "exercise_user_answers", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_user_answers_user_id"), table_name="exercise_user_answers")
    op.drop_index(op.f("ix_exercise_user_answers_id"), table_name="exercise_user_answers")
    op.drop_index(op.f("ix_exercise_user_answers_exercise_id"), table_name="exercise_user_answers")
    op.drop_table("exercise_user_answers")
    # ### end Alembic commands ###
