"""upgrade_answers_table

Revision ID: 22e84fe86fcb
Revises: b3201e22d182
Create Date: 2024-12-29 15:37:02.843803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "22e84fe86fcb"
down_revision: Union[str, None] = "b3201e22d182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("related_files", sa.JSON(), nullable=False))
    op.add_column("answers", sa.Column("question_id", sa.String(length=256), nullable=False))
    op.add_column("answers", sa.Column("question_text", sa.Text(), nullable=False))
    op.add_column("answers", sa.Column("choice_a", sa.Text(), nullable=False))
    op.add_column("answers", sa.Column("choice_b", sa.Text(), nullable=False))
    op.add_column("answers", sa.Column("choice_c", sa.Text(), nullable=False))
    op.add_column("answers", sa.Column("choice_d", sa.Text(), nullable=False))
    op.add_column(
        "answers", sa.Column("user_selected_choice", sa.String(length=256), nullable=False)
    )
    op.add_column("answers", sa.Column("correct_choice", sa.String(length=256), nullable=False))
    op.add_column("answers", sa.Column("is_correct", sa.Boolean(), nullable=False))
    op.add_column("answers", sa.Column("explanation", sa.Text(), nullable=False))
    op.add_column("answers", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("answers", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "answers",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_answers_id"), "answers", ["id"], unique=False)
    op.create_index(op.f("ix_answers_question_id"), "answers", ["question_id"], unique=False)
    op.create_index(
        op.f("ix_exercise_user_answers_id"), "exercise_user_answers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_user_answers_user_id"), "exercise_user_answers", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_user_answers_user_id"), table_name="exercise_user_answers")
    op.drop_index(op.f("ix_exercise_user_answers_id"), table_name="exercise_user_answers")
    op.drop_index(op.f("ix_answers_question_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_id"), table_name="answers")
    op.alter_column(
        "answers",
        "user_id",
        existing_type=sa.String(length=128),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("answers", "updated_at")
    op.drop_column("answers", "created_at")
    op.drop_column("answers", "explanation")
    op.drop_column("answers", "is_correct")
    op.drop_column("answers", "correct_choice")
    op.drop_column("answers", "user_selected_choice")
    op.drop_column("answers", "choice_d")
    op.drop_column("answers", "choice_c")
    op.drop_column("answers", "choice_b")
    op.drop_column("answers", "choice_a")
    op.drop_column("answers", "question_text")
    op.drop_column("answers", "question_id")
    op.drop_column("answers", "related_files")
    # ### end Alembic commands ###
