"""add style column

Revision ID: 33e1bfce096c
Revises: 74e82392f17f
Create Date: 2025-01-19 01:53:20.215438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e1bfce096c'
down_revision: Union[str, None] = '74e82392f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('style', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outputs', 'style')
    # ### end Alembic commands ###
