"""use firebase

Revision ID: 41b7289ead85
Revises: ee7ece65c406
Create Date: 2024-10-07 14:38:07.643811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "41b7289ead85"
down_revision: Union[str, None] = "ee7ece65c406"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("files_ibfk_1", "files", type_="foreignkey")
    op.drop_constraint("notes_ibfk_1", "notes", type_="foreignkey")
    op.drop_constraint("outputs_ibfk_1", "outputs", type_="foreignkey")

    try:
        op.drop_index("ix_users_email", table_name="users")
        op.drop_index("ix_users_id", table_name="users")
        op.drop_index("ix_users_username", table_name="users")
    except Exception:
        pass
    op.alter_column(
        "files",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=128),
        existing_nullable=False,
    )

    op.alter_column(
        "notes",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=128),
        existing_nullable=False,
    )

    op.alter_column(
        "outputs",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    try:
        op.create_index("ix_files_user_id", "files", ["user_id"], unique=False)
        op.create_index("ix_notes_user_id", "notes", ["user_id"], unique=False)
        op.create_index("ix_outputs_user_id", "outputs", ["user_id"], unique=False)
    except Exception:
        pass

    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
            nullable=False,
        ),
        sa.Column(
            "email",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
            nullable=False,
        ),
        sa.Column(
            "password",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_foreign_key("outputs_ibfk_1", "outputs", "users", ["user_id"], ["id"])
    op.drop_index(op.f("ix_outputs_user_id"), table_name="outputs")
    op.alter_column(
        "outputs",
        "user_id",
        existing_type=sa.String(length=128),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.create_foreign_key("notes_ibfk_1", "notes", "users", ["user_id"], ["id"])
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.alter_column(
        "notes",
        "user_id",
        existing_type=sa.String(length=128),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.create_foreign_key("files_ibfk_1", "files", "users", ["user_id"], ["id"])
    op.drop_index(op.f("ix_files_user_id"), table_name="files")
    op.alter_column(
        "files",
        "user_id",
        existing_type=sa.String(length=128),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
