"""make difficulty nullable

Revision ID: 74e82392f17f
Revises: a4d2ee11c335
Create Date: 2025-01-16 09:00:49.714662

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "74e82392f17f"
down_revision: Union[str, None] = "a4d2ee11c335"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercises",
        "difficulty",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=10),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercises",
        "difficulty",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
