"""add_title_column

Revision ID: 7a2fc39f5b0b
Revises: 1f25e371eadc
Create Date: 2024-11-18 15:10:17.891342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2fc39f5b0b'
down_revision: Union[str, None] = '1f25e371eadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'title')
    # ### end Alembic commands ###
