"""add difficulty column in exercise

Revision ID: a4d2ee11c335
Revises: 22e84fe86fcb
Create Date: 2025-01-10 10:54:35.180336

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d2ee11c335"
down_revision: Union[str, None] = "22e84fe86fcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercises", sa.Column("difficulty", sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "difficulty")
    # ### end Alembic commands ###
