"""update answers table

Revision ID: b3201e22d182
Revises: 5dac468e846d
Create Date: 2024-12-27 03:23:51.254195

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b3201e22d182"
down_revision: Union[str, None] = "5dac468e846d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
