steps:
  # Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/nextjs-app",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY",
        "./frontend-nextjs",
      ]
    secretEnv: ["NEXT_PUBLIC_FIREBASE_API_KEY"]

  # ビルドしたイメージを Container Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs-app"]

  # Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    args:
      - "run"
      - "deploy"
      - "ai-notebook-frontend-nextjs"
      - "--image"
      - "gcr.io/$PROJECT_ID/nextjs-app"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY"
      - "--allow-unauthenticated" # 公開アクセスを許可する場合
    secretEnv: ["NEXT_PUBLIC_FIREBASE_API_KEY"]

# ビルドログを保存するバケットを指定
options:
  logging: CLOUD_LOGGING_ONLY

# 使用するイメージ
images:
  - "gcr.io/$PROJECT_ID/nextjs-app"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_API_KEY"
