steps:
  # Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -t gcr.io/$PROJECT_ID/nextjs-app --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET --build-arg NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS=$$NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS --build-arg NEXT_PUBLIC_BACKEND_HOST=$$NEXT_PUBLIC_BACKEND_HOST ./frontend-nextjs",
      ]
    secretEnv:
      [
        "NEXT_PUBLIC_FIREBASE_API_KEY",
        "NEXT_PUBLIC_FIREBASE_APP_ID",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
        "NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS",
        "NEXT_PUBLIC_BACKEND_HOST"
      ]

  # ビルドしたイメージを Container Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker push gcr.io/$PROJECT_ID/nextjs-app"]

  # Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    args:
      - "run"
      - "deploy"
      - "ai-notebook"
      - "--image"
      - "gcr.io/$PROJECT_ID/nextjs-app"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - "--set-env-vars"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - "--set-env-vars"
      - "NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS=$$NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS"
      - "--set-env-vars"
      - "NEXT_PUBLIC_BACKEND_HOST=$$NEXT_PUBLIC_BACKEND_HOST"
      - "--allow-unauthenticated" # 公開アクセスを許可する場合
    secretEnv:
      [
        "NEXT_PUBLIC_FIREBASE_API_KEY",
        "NEXT_PUBLIC_FIREBASE_APP_ID",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
        "NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS",
        "NEXT_PUBLIC_BACKEND_HOST"
      ]

# ビルドログを保存するバケットを指定
options:
  logging: CLOUD_LOGGING_ONLY

# 使用するイメージ
images:
  - "gcr.io/$PROJECT_ID/nextjs-app"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_APP_ID"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS/versions/latest
      env: "NEXT_PUBLIC_ALLOWED_EMAIL_DOMAINS"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_BACKEND_HOST/versions/latest
      env: "NEXT_PUBLIC_BACKEND_HOST"


