steps:
  # Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nextjs-app", "./frontend-nextjs"]

  # ビルドしたイメージを Container Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs-app"]

  # Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    args:
      - "run"
      - "deploy"
      - "nextjs-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/nextjs-app"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # 公開アクセスを許可する場合

# ビルドログを保存するバケットを指定
options:
  logging: CLOUD_LOGGING_ONLY

# 使用するイメージ
images:
  - "gcr.io/$PROJECT_ID/nextjs-app"
