"""test migration

Revision ID: 5026a1da26e7
Revises: b6df2ff64f4a
Create Date: 2024-05-28 15:53:05.552121

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5026a1da26e7"
down_revision: Union[str, None] = "b6df2ff64f4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
