name: Sphinx

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: pip install sphinx sphinx-rtd-theme myst-parser
      - name: Sphinx build frontend
        run: sphinx-apidoc -f -o frontend/docs/source/ frontend/app/
      - name: Make HTML frontend
        run: sphinx-build frontend/docs/source/ docs/frontend/ -a
      - name: Sphinx build backend
        run: sphinx-apidoc -f -o backend/docs/source/ backend/app/
      - name: Make HTML backend
        run: sphinx-build backend/docs/source/ docs/backend/ -a
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m 'Update documentation'
          git push origin gh-pages
